name: Test

on:
  push:
    branches-ignore: [main]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Install Node.js (supports annotating ESLint errors on commits and pull requests)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: npm
      # Install dependencies
      - name: Install
        run: npm ci
      # Build main and renderer
      - name: Build
        run: npm run build
      # Run ESLint
      - name: Lint
        run: npm run lint
      # Run TypeScript compiler
      - name: TypeScript
        run: npm exec tsc
      # Run tests with Jest
      - name: Test
        run: npm test
